export default {
  // 通用
  pb: "公开服",
  wl: "白名单服",
  submit: "提交",
  check_json: "检查 JSON 源文",
  cancel: "取消",
  confirm: "确认",
  passed: "通过",
  error: "异常",
  close: "关闭",
  aiWarn: "警告：此语言由 腾讯元宝-混元AI模型 生成，可能含有用词、语法错误等\n如果发现问题，可以在 GitHub 上提交 issue",

  // 标题栏
  header1: "Teas Official 后台管理中心",
  not_login: "暂未登录",

  // 主页左侧抽屉栏
  ca_sj: "SourceJump 记录上传",
  ca_nearly_record1: "近期记录列表",
  ca_nearly_record2: "只会显示最近15个记录",
  ca_mapdownload1: "地图下载",
  ca_mapdownload2: "下载至服务器，目前仅支持WL服",
  ca_logs: "用户操作日志",
  ca_watch_replay: "在线观看回放",
  ca_about1: "关于",
  ca_about2: "更新履历 & 版本号",
  ca_dev1: "开发调试页面",
  ca_dev2: "身份验证通过，巴别塔欢迎您！",

  // 登录页
  welcome: "欢迎访问！",
  language: "选择语言",
  guest: "游客，请登录！",
  login_alert1: "严禁恶意上传数据，违者撤销访问权限！",
  login_alert2: "若误操作，请联系SourceJump管理员，而不是我们！",
  login_token: "登录代号",
  login: "登录",
  logout: "登出",

  // SJ 上传页
  sj_title: "SourceJump 记录上传 ",
  sj_subtitle1: "可以在左侧菜单中找到",
  sj_subtitle2: "并完成自动填充",
  sj_name: "记录持有者名称",
  sj_name_hint: "填写你当前的Steam名称",
  sj_steamid_hint: "需要填写SteamID3，示例：[U:1:322639589]，查询地址：https://steamid.io",
  sj_map: "地图名",
  sj_map_hint: "需要带上前缀，如：bhop_bfur",
  sj_date: "记录时间",
  sj_date_hint: "自动生成，若需要更新请刷新页面",
  sj_strafes: "加速次数",
  sj_strafes_hint: "Strafes",
  sj_jumps: "跳跃次数",
  sj_jumps_hint: "Jumps",
  sj_sync: "同步率",
  sj_sync_hint: "Sync，无需填写百分号",
  sj_time: "记录用时",
  sj_time_hint: "单位：秒",
  submit_confirm: "提交前确认",
  submit_confirm1: "请在提交前确认您的信息：",
  submit_confirm2: "记录持有者：",
  submit_confirm3: "SteamID3：",
  submit_confirm4: "地图：",
  submit_confirm5: "加速 跳跃 同步率：",

  // 地图下载
  mapmanage: "地图管理",
  mp_subtitle1: "因时间问题，暂未实现心跳包与重连机制，在看到",
  mp_subtitle2: "前请确保网页畅通，不要刷新网页或切换标签！！！",
  mp_map: "地图名",
  mp_map_hint: "需要在 fastdl.me 中可用",
  mp_do: "下载地图",
  mp_rm: "删除地图",
  mp_complete: "任务已完成，现在您可以安全的退出本页面！",
  mp_doed: "已下载：",
  mp_rm_fail: "删除失败：",
  mp_cr_sess: "创建线程...",
  mp_fl_link: "连接至下载服务器...",
  mp_downloading: "下载中...",
  mp_unzip: "解压文件中...",
  mp_write: "写入文件中...",
  mp_notif_ok: "任务完成！",

  // 在线记录回放
  rp_title: "记录播放器",
  rp_subtitle: "注意：部分地图可能存在大量紫黑格子，或完全无法加载的问题，将在未来修复！",
  rp_map: "地图名",
  rp_map_hint: "搜索一个记录",
  rp_e3: "未验证",
  rp_e0: "已验证",
  rp_e1: "材质丢失",
  rp_e2: "地图损坏"
}
